apiVersion: apps/v1
kind: Deployment
metadata:
  name: __DB_DEPLOYMENT__
  namespace: __NAMESPACE__
spec:
  replicas: __DB_REPLICAS__
  selector:
    matchLabels:
      app: __DB_DEPLOYMENT__
  template:
    metadata:
      labels:
        app: __DB_DEPLOYMENT__
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: __DB_SECRET__
                  key: MSSQL_SA_PASSWORD
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: __DB_DEPLOYMENT__-pvc
