apiVersion: v1
kind: Secret
metadata:
  name: __DB_SECRET__
  namespace: __NAMESPACE__
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: "__MSSQL_SA_PASSWORD__"
  CONNECTION_STRING: "Server=__DB_SERVICE__,1433;Database=__DB_NAME__;User Id=sa;Password=__MSSQL_SA_PASSWORD__;TrustServerCertificate=True;"
